spring:
#Configuraci\u00f3n MySQL
 datasource:
  url: jdbc:mysql://localhost:3306/mirosario?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
#Configuraci\u00f3n Creaci\u00f3n de tablas (Hibernate)
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#Para que thymeleaf no guarde datos en cache
 thymeleaf:
  cache: false
